# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: mkdocs.yml
      - id: check-toml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.3
    hooks:
      - id: ruff
        args: [ --fix, --unsafe-fixes, --exit-non-zero-on-fix ]
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.4.3
    hooks:
      # Run the pip compile
      - id: pip-compile
        name: pip-compile requirements.in
        args: [ pyproject.toml, -U, -o, requirements.txt ]
        files: requirements/requirements.in

#  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
#    rev: v9.17.0
#    hooks:
#      - id: commitlint
#        stages: [ commit-msg ]
#        additional_dependencies:
#          - 'commitlint-config-gitmoji'
