site_name: Depthai Yolo
site_url: https://richard-xx.github.io/DepthAI_Yolo/
edit_uri: /blob/main/docs/

# Repository
repo_name: richard-xx/DepthAI_Yolo
repo_url: https://github.com/richard-xx/DepthAI_Yolo


theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.tabs  #主题插件：顶部横向导航栏
    - navigation.tabs.sticky
    - navigation.top   #主题插件：快速回到页首
    - navigation.tracking
    - navigation.path
    - search.suggest
    - search.highlight
    - toc.follow
    - toc.integrate

  language: 'zh'         #页面文字

  palette:
    # 自动模式的调色板切换
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # 浅色模式的调色板切换
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # 深色模式的调色板切换
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - mkdocs-typer
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: false
      linenums: false
      line_spans: __span
      pygments_lang_class: true

  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

plugins:
  - search:
      separator: '[\s\u200b\-]'

nav:
  - Home: index.md
  - Oak Custom Docs: https://richard-xx.github.io/oak_custom_doc/oak/pointcloud/point_cloud_viewer/
  - Yolo:
    - OAK D: oak-d.md
    - OAK SR: sr.md
    - OAK LR: lr.md
